### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by matt-stevenson** [317070/Twitch-plays-LSD-neural-net#3]
I have all dependencies installed and I am able to run train_image.py using the hd1.jpg image successfully.  However if I change the starting image to anything with a width or height less than 896px I get an error:

> image shape: (1, 3, 576, 1024)
> Traceback (most recent call last):
>  File "train_image.py", line 218, in <module>
>    loss, l = iter_train(0)
>  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in **call**
>    storage_map=self.fn.storage_map)
>  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in **call**
>    outputs = self.fn()
> RuntimeError: Could not set tensor4d descriptor: CUDNN_STATUS_BAD_PARAMshapes=1 4096 0 4 strides=0 0 4 1
> Apply node that caused the error: GpuDnnConv{workmem='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, >GpuAlloc{memset_0=True}.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='cross'}.0, Constant{1.0}, Constant{0.0})
> Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7efe862a7990>, Scalar(float32), Scalar(float32)]
> Inputs shapes: [(1, 512, 6, 10), (4096, 512, 7, 7), (1, 4096, 0, 4), 'No shapes', (), ()]
> Inputs strides: [(0, 60, 10, 1), (25088, 49, 7, 1), (0, 0, 4, 1), 'No strides', (), ()]
> Inputs values: ['not shown', 'not shown', <CudaNdarray object at 0x7efe4ee2a830>, <PyCObject object at 0x7efe4eea7918>, 1.0, 0.0]`

Another problem comes up when running train.py:

> features activated: 
> [331]
> Buffer underflow? 0
> Traceback (most recent call last):
>  File "train.py", line 202, in <module>
>    newframe = stream.send_frame( np.transpose(x.get_value()[0]/255.0,(1,2,0)), text=string )
>  File "/usr/local/Twitch-plays-LSD-neural-net/zoomingstream.py", line 303, in send_frame
>    return zoom(frame, frames_before_next_image)
>  File "/usr/local/Twitch-plays-LSD-neural-net/zoomingstream.py", line 125, in zoom
>    frame_rotated = fast_warp(frame, (tf_shift_inv + (tf_rotate + tf_shift)).params,
> AttributeError: 'SimilarityTransform' object has no attribute 'params'`

I suspect these problems may be due to dependency version differences.  
What versions of Theano and skimage are you using?  I'd like to test with the same versions you are using, or at least have the older version to compare the code and help debug.

I have a newer version of Lasagne and was able to fix the obvious problems of field names.   I am also running the latest NVidia drivers and CUDA libraries to support the gtx980 ti, hopefully those do not have any problems.

**Comment by matt-stevenson** [comment]
In skimage 0.7.1 you must use SimilarityTransform._matrix instead of SimilarityTransform.params.

I am still not sure what is the source of the first problem running train_image.py with smaller images, however I am able to run train.py with smaller images and stream the output to twitch without an issue.  I think the problem is related to pool_size array setup.
